apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-workspace
spec:
  workspaces:
    - name: source
  steps:
    - name: debug
      image: alpine
      securityContext:
        runAsUser: 0 # Run as root if necessary
      script: |
        #!/bin/sh
        echo "Checking for processes using /workspace/source"
        lsof /workspace/source || echo "No processes found or lsof not available"
        echo "Directory contents:"
        ls -la /workspace/source
    - name: clean
      image: alpine
      securityContext:
        runAsUser: 0 # Run as root if necessary
      script: |
        #!/bin/sh
        echo "start remove /workspace/*"
        rm -rf /workspace/output/*