apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
spec:
  workspaces:
    - name: source
  params:
    - name: GOALS
      type: string
  steps:
    - name: maven
      image: maven:3.8.5-openjdk-17
      securityContext:
        runAsUser: 0 # Run as root if necessary
      workingDir: $(workspaces.source.path)
      command: ["mvn"]
      args: ["$(params.GOALS)"]
